name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install uv
      uses: supplypike/setup-bin@v3
      with:
        uri: https://github.com/astral-sh/uv/releases/latest/download/uv-x86_64-unknown-linux-gnu.tar.gz
        name: uv
        version: latest

    - name: Install dependencies
      run: |
        uv venv
        . .venv/bin/activate
        uv pip install -r <(python -m pip freeze --exclude-editable)

    - name: Build package
      run: |
        . .venv/bin/activate
        python -m build

    - name: Publish to PyPI with uv
      env:
        UV_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        . .venv/bin/activate
        uv publish --token $UV_PYPI_TOKEN
